version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install for static site"
  build:
    commands:
      - echo "No build step required for static HTML/JS"
  post_build:
    commands:
      - echo "Deploying static site to S3"
      - aws s3 sync . s3://photo-album-frontend-2025 --exclude "buildspec.yml" --delete
artifacts:
  files:
    - '**/*'
